# theme.toml

name = "Death by Numbers"
license = "MIT"
licenselink = "https://github.com/chnm/bom/bom-website/blob/master/LICENSE"
description = "Theme for the Death by Numbers project at the Roy Rosenzweig Center for History and New Media"
homepage = "https://deathbynumbers.org/"
min_version = "0.41.0"

[author]
  name = "Roy Rosenzweig Center for History and New Media"
  homepage = "https://rrchnm.org"
  version = 0.8

[taxonomies]
    tag = "tags"
    category = "categories"
    author = "authors"