baseURL: 'https://deathbynumbers.org'
languageCode: 'en-us'
title: 'Death by Numbers'
description: >-
  Death by Numbers is a digital scholarly research project on the London Plague Bills 
  by the Roy Rosenzweig Center for History and New Media
copyright: 2021-2023

permalinks:
  blog: '/:year/:month/:day/:slug/'
  archive: '/:slug/'
  page: '/:section/:slug/'

theme: 'dbn'

author:
  name: Roy Rosenzweig Center for History and New Media
  email: webmaster@chnm.gmu.edu

# We need this set for TailwindCSS
build:
  writeStats: true

# We need this for embedding visualizations
markup:
  goldmark:
    renderer:
      unsafe: true

sitemap:
  changefreq: weekly
  priority: 0.5
  filename: sitemap.xml

taxonomies:
  category: categories
  tag: tags
  author: author