name: "[bom-website] Build, Release, Deploy"

on:
  push:
    branches:
      - "preview"
      - "main"
    paths:
      - "bom-website/**"

jobs:
  hugo-build-release-deploy:
    uses: chnm/.github/.github/workflows/hugo--build-release-deploy.yml@main
    secrets: inherit
    with:
      container-registry: "ghcr.io"
      container-image-name: "bom-website"
      hugo-context-root: "."
      hugo-devl-url: "https://dev.deathbynumbers.org"
      hugo-prod-url: "https://deathbynumbers.org"
      
      build-artifact-name: "bom-website"
      release-tag-name-type: "iso"
      
      website-devl-fqdn: "dev.deathbynumbers.org"
      website-prod-fqdn: "deathbynumbers.org"
